version: '3'

services:
  app:
    build:
      context: .
      args:
        PHP_VERSION: $PHP_VERSION
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - "app-storage:/var/www"
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "app-storage:/var/www"
      - "./configs/nginx-default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel-network
    depends_on: 
      - app

  dbs:
    image: mysql:5.7.22
    container_name: dbs
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_DATABASE: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - "dbs-storage:/var/lib/mysql"
      - "./configs/my.cnf:/etc/mysql/my.cnf"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  app-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/storage/app-storage"
  dbs-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/storage/dbs-storage"